---
- name: Install GitLab GPG key (Debian)
  apt_key:
    state: present
    url: https://packages.gitlab.com/gpg.key
  when: ansible_os_family == 'Debian'
  tags:
    - gitlab
    - gitlabgpg

- name: Install GitLab CE (Debian)
  apt:
    name: gitlab-ce
    state: latest
    update_cache: yes
  notify:
    - reconfigure gitlab
    - restart gitlab
    - wait for unicorn
  tags:
    - gitlab
    - gitlabupdate
