---
- name: Install Gitlab deps
  yum: name={{ item }} state=latest
  with_items:
    - postfix
  tags: [ 'gitlab' , 'yum' ]

- name: Enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - postfix
  tags: gitlab

- name: Configure mail relay
  lineinfile: dest=/etc/postfix/main.cf
              state=present
              insertafter='#relayhost = '
              line='relayhost = [{{ mail_relay }}]'
  notify: restart postfix
  tags: gitlab

- name: Check if Gitlab is already installed
  command: rpm -q gitlab
  register: gitlab_status
  ignore_errors: true
  tags: gitlab

- name: Create /etc/gitlab
  file: state=directory
        path=/etc/gitlab
        owner=root
        group=root
        mode=0700
  tags: gitlab

- name: Copy gitlab.rb
  template: src=gitlab.rb.j2
            dest=/etc/gitlab/gitlab.rb
            owner=root
            group=root
            mode=0600
  notify: reconfigure gitlab
  tags: gitlab

- name: Copy SSL gitlab.crt
  copy: src=gitlab.crt
        dest=/etc/pki/tls/private/gitlab.crt
        owner=root
        group=root
        mode=0644
  tags: gitlab

- name: Copy SSL gitlab.key
  template: src=gitlab.key.j2
            dest=/etc/pki/tls/private/gitlab.key
            owner=root
            group=root
            mode=0600
  tags: gitlab

- {include: update-gitlab.yml, when: 'gitlab_status.stdout != "gitlab-{{ gitlab_version }}.el6.x86_64"'}
