---
- name: Check if Gitlab is already installed
  command: rpm -q gitlab
  register: gitlab_status
  ignore_errors: true
  tags: gitlab

- name: Create /etc/gitlab
  file: state=directory
        path=/etc/gitlab
        owner=root
        group=root
        mode=0775
  tags: gitlab

- name: Copy gitlab.rb
  template: src=gitlab.rb.j2
            dest=/etc/gitlab/gitlab.rb
            owner=root
            group=root
            mode=0600
  notify: reconfigure gitlab
  tags: gitlab

- name: Copy SSL gitlab.crt
  template: src=gitlab.crt.j2
        dest={{ ssl_cert_path }}/gitlab.crt
        owner=root
        group=root
        mode=0644
  tags: gitlab

- name: Copy SSL gitlab.key
  template: src=gitlab.key.j2
            dest={{ ssl_key_path }}/gitlab.key
            owner=root
            group=root
            mode=0600
  tags: gitlab

- {include: update-gitlab.yml, when: 'gitlab_status.stdout != "gitlab-{{ gitlab_version }}.el6.x86_64"'}
