---
- name: UPDATE | Stop unicorn, sidekiq, and nginx
  command: gitlab-ctl stop {{ item }}
  when: "'not installed' not in gitlab_status.stdout"
  with_items:
    - unicorn
    - sidekiq
    - nginx
  register: status_check
  changed_when: "': 0s' in status_check.stdout"
  tags: [ "gitlab" , "gitlabupdate" ]

- name: UPDATE | Backup database
  command: gitlab-rake gitlab:backup:create
  when: "'not installed' not in gitlab_status.stdout"
  tags: [ "gitlab" , "gitlabupdate" ]

- name: UPDATE | Download GitLab package
  get_url:
    url: "{{ gitlab_package_url }}"
    dest: "/tmp/"
  tags: [ "gitlab" , "gitlabupdate" , "debug" ]

- name: UPDATE | Install GitLab
  command: "{{ gitlab_install_command }} /tmp/{{ gitlab_package }}.{{ gitlab_package_extension }}"
  tags: [ "gitlab" , "gitlabupdate" ]

- name: UPDATE | Remove GitLab package
  file:
    dest: "/tmp/{{ gitlab_package}}.{{ gitlab_package_extension }}"
    state: absent
  notify:
    - reconfigure gitlab
    - restart gitlab
    - wait for unicorn
    - set SELinux context of gitlab home direcotry
  tags: [ "gitlab" , "gitlabupdate" ]
