---
- name: UPDATE | Stop unicorn, sidekiq, and nginx
  command: gitlab-ctl stop {{ item }}
  when: "'not installed' not in gitlab_status.stdout"
  with_items:
    - unicorn
    - sidekiq
    - nginx
  register: status_check
  changed_when: "': 0s' in status_check.stdout"
  tags: [ "gitlab" , "gitlabupdate" ]

- name: UPDATE | Backup database
  command: gitlab-rake gitlab:backup:create
  when: "'not installed' not in gitlab_status.stdout"
  tags: [ "gitlab" , "gitlabupdate" ]

- name: UPDATE | Download GitLab rpm
  get_url:
    url: "https://downloads-packages.s3.amazonaws.com/centos-6.6/gitlab-{{ gitlab_version }}.el6.x86_64.rpm"
    dest: "/tmp/gitlab-{{ gitlab_version }}.el6.x86_64.rpm"
  tags: [ "gitlab" , "gitlabupdate" ]

- name: UPDATE | Install GitLab
  command: rpm -Uvh /tmp/gitlab-{{ gitlab_version }}.el6.x86_64.rpm
  tags: [ "gitlab" , "gitlabupdate" ]

- name: UPDATE | Remove GitLab rpm
  file:
    dest: "/tmp/gitlab-{{ gitlab_version }}.el6.x86_64.rpm"
    state: absent
  notify:
    - reconfigure gitlab
    - restart gitlab
    - wait for unicorn
    - set SELinux context of gitlab home direcotry
  tags: [ "gitlab" , "gitlabupdate" ]
